name: Dancing Mountain Arts
favicon: null
layout_spectrum: 0.5045091197825968
typography_spectrum: 0.15111
title: Dancing Mountain Arts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-81379848-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#faf0d8'
    - '#797c5e'
    - '#f5c02c'
    - '#270601'
    - '#8d330d'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
