name: Dancing Mountain Arts
favicon: null
layout_spectrum: 0.5045091197825968
typography_spectrum: 0.2746944488026202
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7764332452788949
  lightness: 0.07641637930646539
  saturation: 0.9943742870818824
  rhythmicContrast: 0.5032286858186126
purpose: []
